name: Test
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: main

jobs:
  test:
    # test the code before pushing into the main
    name: Testing the source code
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v7

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: 1.26
          check-latest: true
          cache: true

      - name: Download Dependencies
        run: go mod download

      - name: Run Unit Tests
        run: make test-unit
